
module.exports = {
  POS_CONNECT: 'POS_CONNECT',
  POS_GET_FUEL_CONFIG: 'POS_GET_FUEL_CONFIG',
  POS_GET_DISPENSER_STATUS: 'POS_GET_DISPENSER_STATUS',
  POS_BASKET_CLEAR: 'POS_BASKET_CLEAR',
  POS_BASKET_SET_PARAMS: 'POS_BASKET_SET_PARAMS',
  POS_BASKET_GET_DATA: 'POS_BASKET_GET_DATA',
  POS_BASKET_FUEL_ADD: 'POS_BASKET_FUEL_ADD',
  POS_BASKET_FUEL_DEL: 'POS_BASKET_FUEL_DEL',
  POS_BASKET_ARTICLE_SET: 'POS_BASKET_ARTICLE_SET',
  POS_BASKET_COUPON_ADD: 'POS_BASKET_COUPON_ADD',
  POS_BASKET_COUPON_DEL: 'POS_BASKET_COUPON_DEL',
  POS_FISCAL_CHECK: 'POS_FISCAL_CHECK',
  POS_GET_CHECK_STATUS: 'POS_GET_CHECK_STATUS',
  POS_COPY_CHECK: 'POS_COPY_CHECK',
  POS_SHIFT_PROC: 'POS_SHIFT_PROC',

  CA_GET_STATUS: 'CA_GET_STATUS',
  CA_START: 'CA_START',
  CA_STOP: 'CA_STOP',
  CA_CLEAR: 'CA_CLEAR',

  BT_GET_COMMAND_STATUS: 'BT_GET_COMMAND_STATUS'
};
